### ISSUE TITLE
The game crashed whilst initializing game Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'primalwinter'!

### ISSUE THREAD

**Issue by Sulkrepress** [alcatrazEscapee/primal-winter#73] opened 2023-01-27 00:03 UTC
using fabric version 1.19.2

**Comment by alcatrazEscapee** [comment] 2023-04-19 14:31
Duplicate of #69

**Closed as completed by alcatrazEscapee** 2023-04-19 14:31 UTC
Labels: duplicate, Version: 1.19.x
