### ISSUE TITLE
Server crash with mod

### ISSUE THREAD

**Issue by Fadhvile** [alcatrazEscapee/primal-winter#68] opened 2022-12-05 16:15 UTC
I try to made a server with the mod, and it'll just crash, I tried removing the mod one by one and find the server will turn on just fine without primalwinter.

Im using the forge-1.18.2-3.1.0. Version, here is the log

https://mclo.gs/rMl17YS

**Comment by Fadhvile** [comment] 2022-12-05 22:21
I decide to test run again, but using the version forge-1.18.2-3.0.2, the server start fine

**Comment by alcatrazEscapee** [comment] 2023-04-19 14:31
Duplicate of #69

**Closed as completed by alcatrazEscapee** 2023-04-19 14:31 UTC
Labels: duplicate, Version: 1.19.x
