### ISSUE TITLE
Snow and ice generates above nether bedrock

### ISSUE THREAD

**Issue by River25** [alcatrazEscapee/primal-winter#4] opened 2020-08-07 03:09 UTC
This happens most of the time if you go above the nether bedrock however sometimes it doesn't appear automatically if the chunk is not loaded.

**Comment by alcatrazEscapee** [comment] 2020-08-07 11:41
Minecraft version?
Forge or Fabric?
Mod version?

**Comment by River25** [comment] 2020-08-07 18:32
Minecraft Version: 1.16.1
Fabric    Version: 0.8.9
Mod Version primalwinter-fabric-1.16.1-1.0.0.jar

**Comment by alcatrazEscapee** [comment] 2020-08-22 21:32
I cannot reproduce. Have you made sure that the nether biomes are blacklisted from winter transformations in the config?

```toml
nonWinterBiomes = "minecraft:the_end,minecraft:small_end_islands,minecraft:end_barrens,minecraft:end_highlands,minecraft:end_midlands,minecraft:nether_wastes,minecraft:soul_sand_valley,minecraft:crimson_forest,minecraft:warped_forest,minecraft:basalt_deltas"
```

**Comment by alcatrazEscapee** [comment] 2020-08-25 22:33
In any case, should be resolved by https://github.com/alcatrazEscapee/primal-winter/releases/tag/v1.1.0-fabric

**Closed as completed by alcatrazEscapee** 2020-08-25 22:33 UTC
Labels: Version: 1.16.x Fabric
